/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-19 03:14:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.project4.bean.SubjectBean;
import in.co.rays.project4.bean.CollegeBean;
import in.co.rays.project4.bean.CourseBean;
import java.util.List;
import in.co.rays.project4.util.HTMLUtility;
import java.util.HashMap;
import in.co.rays.project4.controller.FacultyCtl;
import in.co.rays.project4.util.DataUtility;
import in.co.rays.project4.util.ServletUtility;
import in.co.rays.project4.bean.RoleBean;
import in.co.rays.project4.controller.*;
import in.co.rays.project4.bean.UserBean;

public final class FacultyView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1637060407003L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1636632921369L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("in.co.rays.project4.controller");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.co.rays.project4.util.ServletUtility");
    _jspx_imports_classes.add("in.co.rays.project4.bean.CollegeBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.co.rays.project4.bean.SubjectBean");
    _jspx_imports_classes.add("in.co.rays.project4.util.HTMLUtility");
    _jspx_imports_classes.add("in.co.rays.project4.bean.UserBean");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("in.co.rays.project4.controller.FacultyCtl");
    _jspx_imports_classes.add("in.co.rays.project4.util.DataUtility");
    _jspx_imports_classes.add("in.co.rays.project4.bean.CourseBean");
    _jspx_imports_classes.add("in.co.rays.project4.bean.RoleBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16*16\"/>\r\n");
      out.write("<title> Faculty Registration Page</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<!-- <script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#datepicker\").datepicker({\r\n");
      out.write("			dateFormat : 'dd/MM/yy',\r\n");
      out.write("			changeMonth : true,\r\n");
      out.write("			changeYear : true,\r\n");
      out.write("			yearRange : \"1980:2002\",\r\n");
      out.write("		//maxDate:'0',\r\n");
      out.write("		// minDate:0\r\n");
      out.write("		//yearRange : \"-40:-18\"\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script> -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      in.co.rays.project4.bean.FacultyBean bean = null;
      bean = (in.co.rays.project4.bean.FacultyBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new in.co.rays.project4.bean.FacultyBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("	<form action=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>jQuery UI Datepicker - Display month &amp; year menus</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#datepicker\").datepicker({\r\n");
      out.write("			changeMonth : true,\r\n");
      out.write("			changeYear : true,\r\n");
      out.write("		//	yearRange : '1970:2030'\r\n");
      out.write("			maxDate: '12/31/2003',\r\n");
      out.write("			minDate: '01/01/1981',\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");

	UserBean userBean = (UserBean) session.getAttribute("user");

	boolean userLoggedIn = userBean != null;

	String welcomeMsg = "Hi, ";

	if (userLoggedIn) {
		String role = (String) session.getAttribute("role");
		welcomeMsg += userBean.getFirstName() + " (" + role + ")";
	} else {
		welcomeMsg += "Guest";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"90%\"><a href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\">Welcome</a> |\r\n");
      out.write("			");

			if (userLoggedIn) {
		
      out.write(" <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\">Logout</b></a>\r\n");
      out.write("\r\n");
      out.write("			");

				} else {
			
      out.write(" <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\">Login</b></a> ");

 	}
 
      out.write("</td>\r\n");
      out.write("		<td rowspan=\"2\">\r\n");
      out.write("\r\n");
      out.write("			<center>\r\n");
      out.write("				<h1 align=\"right\">\r\n");
      out.write("					<img src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/rays.jpg\" width=\"318\"\r\n");
      out.write("						height=\"75\">\r\n");
      out.write("				</h1>\r\n");
      out.write("			</center>\r\n");
      out.write("		</td>\r\n");
      out.write("\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>\r\n");
      out.write("			<h3>");
      out.print(welcomeMsg);
      out.write("</h3>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

		if (userLoggedIn) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"2\"> <a href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\">MyProfile</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\">Change Password</b></a>\r\n");
      out.write("		 |<a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\">Get\r\n");
      out.write("				Marksheet</b>\r\n");
      out.write("		</a> | <a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\">Marksheet Merit\r\n");
      out.write("				List</b> </a>\r\n");
      out.write("		 ");

 	if (userBean.getRoleId() == RoleBean.ADMIN) {
 
      out.write("| <a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\">Add Marksheet</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">Marksheet List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\">Add User</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\">User List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\">Add College</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">Add Student</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\">Add Role</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\">Role List</b></a> |<a\r\n");
      out.write("			href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\">Add Course</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\">Course List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\">Add Subject</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\">Subject List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\">Add TimeTable</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\">TimeTable List</b></a>| <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\">Add Faculty</b></a>| <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\">Faculty List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.JAVA_DOC_VIEW);
      out.write("\"  target=\"blank\">Java Doc</b></a> | \r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("			");

            if  (userBean.getRoleId() == RoleBean.STUDENT) {
        
      out.write(" \r\n");
      out.write("       \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COURSE_LIST_CTL );
      out.write("\">Course List</b></a> |       \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL );
      out.write("\">Subject List</b></a> |       \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.FACULTY_LIST_CTL );
      out.write("\">Faculty List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\">TimeTable List</b></a> |\r\n");
      out.write("       ");

     		}
 		
      out.write("\r\n");
      out.write("		\r\n");
      out.write(" 		");

 		if (userBean.getRoleId()  == RoleBean.KIOSK) {
        
      out.write(" \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\">TimeTable List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COURSE_LIST_CTL );
      out.write("\">Course List</b></a> |       \r\n");
      out.write("       ");

     		}
 		
      out.write("\r\n");
      out.write(" 		\r\n");
      out.write(" 		 ");

            if  (userBean.getRoleId()  == RoleBean.COLLEGE_SCHOOL) {
           
          
      out.write(" \r\n");
      out.write("       \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\">Add Marksheet</b></a> |       \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">Marksheet List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">Add Student</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.FACULTY_LIST_CTL );
      out.write("\">Faculty List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\">TimeTable List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COURSE_LIST_CTL );
      out.write("\">Course List</b></a> |       \r\n");
      out.write("       ");

     		}
 		
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("\r\n");
      out.write("	</tr>\r\n");
      out.write("	");

		}
	
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<hr>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");

			List<CollegeBean> colist = (List<CollegeBean>) request.getAttribute("CollegeList");
			List<CourseBean> clist = (List<CourseBean>) request.getAttribute("CourseList");
			List<SubjectBean> slist = (List<SubjectBean>) request.getAttribute("SubjectList");
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<center>\r\n");
      out.write("			<h1>\r\n");
      out.write("			");
 if(bean != null && bean.getId() >0) {
      out.write("\r\n");
      out.write("				<tr><th> Update Faculty </th></tr>\r\n");
      out.write("			");
}else{ 
      out.write("\r\n");
      out.write("			<tr><th> Add Faculty </th></tr>\r\n");
      out.write("			");
} 
      out.write("\r\n");
      out.write("			</h1>\r\n");
      out.write("			<div>\r\n");
      out.write("				<h2><font color=\"green\">");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("</font>\r\n");
      out.write("					<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("</font>\r\n");
      out.write("				</h2>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<input type=\"hidden\" name=\"id\" value=");
      out.print(bean.getId());
      out.write("> <input\r\n");
      out.write("				type=\"hidden\" name=\"createdby\" value=");
      out.print(bean.getCreatedBy());
      out.write(">\r\n");
      out.write("			<input type=\"hidden\" name=\"modifiedby\"\r\n");
      out.write("				value=");
      out.print(bean.getModifiedBy());
      out.write("> <input type=\"hidden\"\r\n");
      out.write("				name=\"createdDatetime\"\r\n");
      out.write("				value=");
      out.print(DataUtility.getStringData(bean.getCreatedDatetime()));
      out.write(">\r\n");
      out.write("			<input type=\"hidden\" name=\"modifiedDatetime\"\r\n");
      out.write("				value=");
      out.print(DataUtility.getStringData(bean.getModifiedDatetime()));
      out.write(">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<table>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\" >CollegeName <span style=\"color: red\">*</span></th>\r\n");
      out.write("					<td >");
      out.print(HTMLUtility.getList("collegeid", String.valueOf(bean.getCollege_id()), colist));
      out.write("\r\n");
      out.write("					</td><td><td style=\"position: fixed\">\r\n");
      out.write("					<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("collegeid", request));
      out.write("</font>\r\n");
      out.write("					\r\n");
      out.write("					</td>\r\n");
      out.write("					\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr><th style=\"padding: 3px\"></th></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("					<th align=\"left\">CourseName <span style=\"color: red\">*</span></th>\r\n");
      out.write("					<td>");
      out.print(HTMLUtility.getList("courseid", String.valueOf(bean.getCourse_id()), clist));
      out.write("\r\n");
      out.write("					</td><td><td style=\"position: fixed\">\r\n");
      out.write("						<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("courseid", request));
      out.write("</font>\r\n");
      out.write("					\r\n");
      out.write("				\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("<tr><th style=\"padding: 3px\"></th></tr> \r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\">SubjectName <span style=\"color: red\">*</span></th>\r\n");
      out.write("					<td>");
      out.print(HTMLUtility.getList("subjectid", String.valueOf(bean.getSubject_id()), slist));
      out.write("\r\n");
      out.write("					</td><td><td style=\"position: fixed\">\r\n");
      out.write("					\r\n");
      out.write("					<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("subjectid", request));
      out.write("</font>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("<tr><th style=\"padding: 3px\"></th></tr> \r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\">FirstName <span style=\"color: red\">*</span>\r\n");
      out.write("					</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"firstname\"\r\n");
      out.write("						placeholder=\" Enter First Name\" size=\"23\" \r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getFirst_Name()));
      out.write("\">\r\n");
      out.write("						</td><td><td style=\"position: fixed\">\r\n");
      out.write("				\r\n");
      out.write("				<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("firstname", request));
      out.write("</font>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("<tr><th style=\"padding: 3px\"></th></tr> \r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\">LastName <span style=\"color: red\">*</span></th>\r\n");
      out.write("					<td><input type=\"text\" name=\"lastname\"\r\n");
      out.write("						placeholder=\" Enter last Name\" size=\"23\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getLast_Name()));
      out.write("\"></td><td><td style=\"position: fixed\">\r\n");
      out.write("					\r\n");
      out.write("					 <font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("lastname", request));
      out.write("</font>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("<tr><th style=\"padding: 3px\"></th></tr> \r\n");
      out.write("								<tr>\r\n");
      out.write("					<th align=\"left\">LoginId <span style=\"color: red\">*</span></th>\r\n");
      out.write("					<td><input type=\"text\" name=\"loginid\"\r\n");
      out.write("						placeholder=\" Enter Login Id\" size=\"23\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getEmail_id()));
      out.write("\"></td><td><td style=\"position: fixed\">\r\n");
      out.write("					\r\n");
      out.write("					<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("loginid", request));
      out.write("</font>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("<tr><th style=\"padding: 3px\"></th></tr> \r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\">Gender <span style=\"color: red\">*</span></th>\r\n");
      out.write("					<td>\r\n");
      out.write("							");

							HashMap map = new HashMap();
							map.put("Male", "Male");
							map.put("Female", "Female");

							String hlist = HTMLUtility.getList("gender", String.valueOf(bean.getGender()), map);
						
      out.write(' ');
      out.print(hlist);
      out.write("</td><td><td style=\"position: fixed\">\r\n");
      out.write("					<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("gender", request));
      out.write("</font>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("<tr><th style=\"padding: 3px\"></th></tr> \r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\">Date Of Joining<font color=\"red\">*</font></th>\r\n");
      out.write("					<td ><input type=\"text\"  name=\"doj\"  id=\"datepicker\"size=\"23\"\r\n");
      out.write("						placeholder=\"Enter Date Of joining\" readonly=\"readonly\"\r\n");
      out.write("						\r\n");
      out.write("						  value=\"");
      out.print(DataUtility.getDateString(bean.getDOJ()));
      out.write("\"></td><td><td style=\"position: fixed\">\r\n");
      out.write("						&nbsp;<font style=\";\" color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("doj", request));
      out.write("</font></td>\r\n");
      out.write(" 				</tr> \r\n");
      out.write("<tr><th style=\"padding: 3px\"></th></tr> \r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\">Qualification <span style=\"color: red\">*</span></th>\r\n");
      out.write("					<td><input type=\"text\" name=\"qualification\" size=\"23\"\r\n");
      out.write("						placeholder=\" Enter Qualification\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getQualification()));
      out.write("\">\r\n");
      out.write("						</td><td><td style=\"position: fixed\">\r\n");
      out.write("					<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("qualification", request));
      out.write("</font>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("<tr><th style=\"padding: 3px\"></th></tr> \r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\">MobileNo <span style=\"color: red\">*</span></th>\r\n");
      out.write("					<td><input type=\"text\" name=\"mobileno\" size=\"23\" maxlength=\"10\"\r\n");
      out.write("						placeholder=\" Enter Mobile No\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getMobile_No()));
      out.write("\"></td><td><td style=\"position: fixed\">\r\n");
      out.write("					<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("mobileno", request));
      out.write("</font>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("<tr><th style=\"padding: 3px\"></th></tr> \r\n");
      out.write("				\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th></th>\r\n");
      out.write("					");
 if(bean.getId() >  0){
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					<td>\r\n");
      out.write("					<input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyCtl.OP_UPDATE);
      out.write("\"> \r\n");
      out.write("					 <input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyCtl.OP_CANCEL);
      out.write("\">\r\n");
      out.write("					</td>\r\n");
      out.write("					");
}else{ 
      out.write("\r\n");
      out.write("					<td> \r\n");
      out.write("					<input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyCtl.OP_SAVE);
      out.write("\"> \r\n");
      out.write("					 <input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyCtl.OP_RESET);
      out.write("\">\r\n");
      out.write("					</td>					\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</center>\r\n");
      out.write("	</form>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style >\r\n");
      out.write("\r\n");
      out.write(".footer{\r\n");
      out.write("position: fixed;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background-color: White;\r\n");
      out.write("  color: black;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  }</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class = \"footer\">\r\n");
      out.write("<HR>\r\n");
      out.write("<H2>&copy; Copyrights RAYS Technologies</H2>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
