/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-11-19 02:40:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.project4.controller.UserCtl;
import java.util.List;
import in.co.rays.project4.util.HTMLUtility;
import java.util.HashMap;
import in.co.rays.project4.util.DataUtility;
import in.co.rays.project4.util.ServletUtility;
import in.co.rays.project4.bean.RoleBean;
import in.co.rays.project4.controller.*;
import in.co.rays.project4.bean.UserBean;

public final class UserView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1637060407003L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1636632921369L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("in.co.rays.project4.controller");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.co.rays.project4.util.ServletUtility");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.co.rays.project4.util.HTMLUtility");
    _jspx_imports_classes.add("in.co.rays.project4.bean.UserBean");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("in.co.rays.project4.util.DataUtility");
    _jspx_imports_classes.add("in.co.rays.project4.controller.UserCtl");
    _jspx_imports_classes.add("in.co.rays.project4.bean.RoleBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write(" <title>Add user</title>   \r\n");
      out.write("		\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/js/CheckBox11.js\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("<!-- <link rel=\"stylesheet\"\r\n");
      out.write("	href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#datepicker\").datepicker({\r\n");
      out.write("			dateFormat : 'MM/dd/yy',\r\n");
      out.write("			//defaultDate : \"06/06/2001\",\r\n");
      out.write("			changeMonth : true,\r\n");
      out.write("			changeYear : true,\r\n");
      out.write("			//yearRange: \"c-20:c+0\",\r\n");
      out.write("			//yearRange : \"1980:2002\",\r\n");
      out.write("		//maxDate:'0',\r\n");
      out.write("		// minDate:0\r\n");
      out.write("		yearRange : \"-40:-18\"\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script> -->\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=\"");
      out.print(ORSView.USER_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>jQuery UI Datepicker - Display month &amp; year menus</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#datepicker\").datepicker({\r\n");
      out.write("			changeMonth : true,\r\n");
      out.write("			changeYear : true,\r\n");
      out.write("		//	yearRange : '1970:2030'\r\n");
      out.write("			maxDate: '12/31/2003',\r\n");
      out.write("			minDate: '01/01/1981',\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");

	UserBean userBean = (UserBean) session.getAttribute("user");

	boolean userLoggedIn = userBean != null;

	String welcomeMsg = "Hi, ";

	if (userLoggedIn) {
		String role = (String) session.getAttribute("role");
		welcomeMsg += userBean.getFirstName() + " (" + role + ")";
	} else {
		welcomeMsg += "Guest";
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"90%\"><a href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\">Welcome</a> |\r\n");
      out.write("			");

			if (userLoggedIn) {
		
      out.write(" <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\">Logout</b></a>\r\n");
      out.write("\r\n");
      out.write("			");

				} else {
			
      out.write(" <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\">Login</b></a> ");

 	}
 
      out.write("</td>\r\n");
      out.write("		<td rowspan=\"2\">\r\n");
      out.write("\r\n");
      out.write("			<center>\r\n");
      out.write("				<h1 align=\"right\">\r\n");
      out.write("					<img src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/rays.jpg\" width=\"318\"\r\n");
      out.write("						height=\"75\">\r\n");
      out.write("				</h1>\r\n");
      out.write("			</center>\r\n");
      out.write("		</td>\r\n");
      out.write("\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td>\r\n");
      out.write("			<h3>");
      out.print(welcomeMsg);
      out.write("</h3>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

		if (userLoggedIn) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"2\"> <a href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\">MyProfile</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\">Change Password</b></a>\r\n");
      out.write("		 |<a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\">Get\r\n");
      out.write("				Marksheet</b>\r\n");
      out.write("		</a> | <a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\">Marksheet Merit\r\n");
      out.write("				List</b> </a>\r\n");
      out.write("		 ");

 	if (userBean.getRoleId() == RoleBean.ADMIN) {
 
      out.write("| <a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\">Add Marksheet</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">Marksheet List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\">Add User</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\">User List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\">Add College</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">Add Student</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\">Add Role</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\">Role List</b></a> |<a\r\n");
      out.write("			href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\">Add Course</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\">Course List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\">Add Subject</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\">Subject List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\">Add TimeTable</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\">TimeTable List</b></a>| <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\">Add Faculty</b></a>| <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\">Faculty List</b></a> | <a\r\n");
      out.write("			href=\"");
      out.print(ORSView.JAVA_DOC_VIEW);
      out.write("\"  target=\"blank\">Java Doc</b></a> | \r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("			");

            if  (userBean.getRoleId() == RoleBean.STUDENT) {
        
      out.write(" \r\n");
      out.write("       \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COURSE_LIST_CTL );
      out.write("\">Course List</b></a> |       \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL );
      out.write("\">Subject List</b></a> |       \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.FACULTY_LIST_CTL );
      out.write("\">Faculty List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\">TimeTable List</b></a> |\r\n");
      out.write("       ");

     		}
 		
      out.write("\r\n");
      out.write("		\r\n");
      out.write(" 		");

 		if (userBean.getRoleId()  == RoleBean.KIOSK) {
        
      out.write(" \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\">TimeTable List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COURSE_LIST_CTL );
      out.write("\">Course List</b></a> |       \r\n");
      out.write("       ");

     		}
 		
      out.write("\r\n");
      out.write(" 		\r\n");
      out.write(" 		 ");

            if  (userBean.getRoleId()  == RoleBean.COLLEGE_SCHOOL) {
           
          
      out.write(" \r\n");
      out.write("       \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\">Add Marksheet</b></a> |       \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">Marksheet List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">Add Student</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.FACULTY_LIST_CTL );
      out.write("\">Faculty List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\">TimeTable List</b></a> |\r\n");
      out.write("        <a href=\"");
      out.print(ORSView.COURSE_LIST_CTL );
      out.write("\">Course List</b></a> |       \r\n");
      out.write("       ");

     		}
 		
      out.write("\r\n");
      out.write("			</td>\r\n");
      out.write("\r\n");
      out.write("	</tr>\r\n");
      out.write("	");

		}
	
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<hr>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\" src=\"../js/calendar.js\"></script>\r\n");
      out.write("		");
      in.co.rays.project4.bean.UserBean bean = null;
      bean = (in.co.rays.project4.bean.UserBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new in.co.rays.project4.bean.UserBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("		");

			List l = (List) request.getAttribute("roleList");
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<center>\r\n");
      out.write("		\r\n");
      out.write("         <h1>\r\n");
      out.write("        	");

        		if( bean != null && bean.getId()>0){
        	
      out.write(" \r\n");
      out.write("        	<tr><th><font>Update User</font></th></tr>\r\n");
      out.write("        	");
 }else{
      out.write("\r\n");
      out.write("        	<tr><th><font>Add User</font></th></tr>\r\n");
      out.write("        	");
 }
      out.write("\r\n");
      out.write("        </h1>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("			<H2>\r\n");
      out.write("				<font color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("\r\n");
      out.write("				</font>\r\n");
      out.write("			</H2>\r\n");
      out.write("\r\n");
      out.write("			<H2>\r\n");
      out.write("				<font color=\"green\"> ");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("\r\n");
      out.write("				</font>\r\n");
      out.write("			</H2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<input type=\"hidden\" name=\"id\" value=\"");
      out.print(bean.getId());
      out.write("\"> \r\n");
      out.write("			 <input type=\"hidden\" name=\"createdBy\" value=\"");
      out.print(bean.getCreatedBy());
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"modifiedBy\"\r\n");
      out.write("				value=\"");
      out.print(bean.getModifiedBy());
      out.write("\"> <input type=\"hidden\"\r\n");
      out.write("				name=\"createdDatetime\"\r\n");
      out.write("				value=\"");
      out.print(DataUtility.getTimestamp(bean.getCreatedDatetime()));
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"modifiedDatetime\"\r\n");
      out.write("				value=\"");
      out.print(DataUtility.getTimestamp(bean.getModifiedDatetime()));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align = \"left\">First Name <font color=\"red\" >* </th>					\r\n");
      out.write("					<td><input type=\"text\" name=\"firstName\" size=\"23\" placeholder=\"Enter  First_Name\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getFirstName()));
      out.write("\"></td><td><td style=\"position: fixed\">\r\n");
      out.write("						<font\r\n");
      out.write("						color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("firstName", request));
      out.write("</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align = \"left\">Last Name<font color=\"red\">*</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"lastName\" size=\"23\"  placeholder=\"Enter  Last_Name\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getLastName()));
      out.write("\"><td><td style=\"position: fixed\"><font\r\n");
      out.write("						color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("lastName", request));
      out.write("</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align = \"left\">LoginId<font color=\"red\">*</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"login\" size=\"23\"  placeholder=\"Enter  Login_id\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getLogin()));
      out.write("\"\r\n");
      out.write("						");
      out.print((bean.getId() > 0) ? "readonly" : "");
      out.write("><td><td style=\"position: fixed\"><font\r\n");
      out.write("						color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("login", request));
      out.write("</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("				");
 if(bean.getId() > 0 && bean != null){ 
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("                   \r\n");
      out.write("                    <td><input type=\"hidden\" name=\"password\" value=\"");
      out.print(DataUtility.getStringData(bean.getPassword()));
      out.write("\"></td>\r\n");
      out.write("                   <td><input type=\"hidden\" name=\"confirmPassword\"  value=\"");
      out.print(DataUtility.getStringData(bean.getPassword()));
      out.write("\"></td>\r\n");
      out.write("                   </tr>\r\n");
      out.write("				");
 }else{ 
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\">Password <font color=\"red\">*</font></th>\r\n");
      out.write("					<td><input type=\"password\" name=\"password\" size=\"23\" placeholder=\"Enter Password\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getStringData(bean.getPassword()));
      out.write("\"></td><td style=\"position: fixed\"><font\r\n");
      out.write("						color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("password", request));
      out.write("</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				                 <tr> \r\n");
      out.write("				                     <th>Confirm Password <font color=\"red\">*</font></th> \r\n");
      out.write("				                     <td><input type=\"password\" name=\"confirmPassword\" size=\"23\" placeholder=\"Confirm Your Password\"\r\n");
      out.write("				                        value=\"");
      out.print(DataUtility.getStringData(bean.getPassword()));
      out.write("\"></td><td style=\"position: fixed\"><font \r\n");
      out.write("				                        color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("confirmPassword", 
				                     request));
      out.write("</font></td> \r\n");
      out.write("				                 </tr> \r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write(" <tr>\r\n");
      out.write("                    <th  align = \"left\">Mobile no. <font color=\"red\">*</th>\r\n");
      out.write("                    <td><input type=\"text\" name=\"mobileNo\" maxlength=\"10\"\r\n");
      out.write("                    size=\"23\"  placeholder=\"Enter  Mobile_no\"\r\n");
      out.write("                     value=\"");
      out.print(DataUtility.getStringData(bean.getMobileNo()));
      out.write("\"></td><td style=\"position: fixed\"><font\r\n");
      out.write("                        color=\"red\"> ");
      out.print(ServletUtility
                    .getErrorMessage("mobileNo", request));
      out.write("</font></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("				             \r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align = \"left\">Gender<font color=\"red\">*</th>\r\n");
      out.write("					<td>\r\n");
      out.write("						");

							HashMap map = new HashMap();
							map.put("Male", "Male");
							map.put("Female", "Female");

							String htmlList = HTMLUtility.getList("gender", String.valueOf( bean.getGender()), map);
						
      out.print(htmlList);
      out.write("\r\n");
      out.write("						 &nbsp;<font style=\"position: fixed;\" color=\"red\">\r\n");
      out.write("							");
      out.print(ServletUtility.getErrorMessage("gender", request));
      out.write("</font>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\">Role<font color=\"red\">*</th>\r\n");
      out.write("					<td>");
      out.print(HTMLUtility.getList("roleId",   String.valueOf(bean.getRoleId()), l));
      out.write("\r\n");
      out.write("\r\n");
      out.write("						&nbsp;<font style=\"position: fixed;\" color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("roleId", request));
      out.write("</font>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("		<tr>		\r\n");
      out.write("			<th align=\"left\">Date Of Birth<font color=\"red\">*</font></th>\r\n");
      out.write("					<td><input type=\"text\"  name=\"dob\"  id=\"datepicker\"\r\n");
      out.write("						placeholder=\"Enter Date Of Birth\"   readonly=\"readonly\" size=\"23\"\r\n");
      out.write("						value=\"");
      out.print(DataUtility.getDateString(bean.getDob()));
      out.write("\">\r\n");
      out.write("						&nbsp;<font style=\"position: fixed;\" color=\"red\"> ");
      out.print(ServletUtility.getErrorMessage("dob", request));
      out.write("</font></td>\r\n");
      out.write("</tr>	\r\n");
      out.write("				\r\n");
      out.write("					<tr>\r\n");
      out.write("					<th></th>\r\n");
      out.write("					");

 	if (bean.getId() > 0) {
 
      out.write("<td colspan=\"2\"> &nbsp; &nbsp; <input type=\"submit\"  name=\"operation\"\r\n");
      out.write("						value=\"");
      out.print(UserCtl.OP_UPDATE);
      out.write("\"> &nbsp; &nbsp; <input type=\"submit\"  name=\"operation\"\r\n");
      out.write("						value=\"");
      out.print(UserCtl.OP_CANCEL);
      out.write("\"></td>\r\n");
      out.write("						");

						} else {
							
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						<td  colspan=\"2\">\r\n");
      out.write("						<input type=\"submit\"  name = \"operation\"  value =\"");
      out.print(UserCtl.OP_SAVE );
      out.write("\">\r\n");
      out.write("						 &nbsp; &nbsp; <input type=\"submit\" name=\"operation\"\r\n");
      out.write("						value=\"");
      out.print(UserCtl.OP_RESET);
      out.write("\"></td>\r\n");
      out.write("							");

						} 
							
      out.write("\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	<br>\r\n");
      out.write("  <br>\r\n");
      out.write("	</center>\r\n");
      out.write("	<\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style >\r\n");
      out.write("\r\n");
      out.write(".footer{\r\n");
      out.write("position: fixed;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background-color: White;\r\n");
      out.write("  color: black;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  }</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class = \"footer\">\r\n");
      out.write("<HR>\r\n");
      out.write("<H2>&copy; Copyrights RAYS Technologies</H2>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
